[features]
seeds = false
skip-lint = false
[programs.localnet]
note_app = "FapTDjVJ6NRjoxaDgxXMofxcVYcwbhZDxS3Lno3ZQiGh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/codezeros/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
